const Genres = [
	'Action',
	'Comedy',
	'Drama',
	'Horror',
	'Thriller',
	'Sci-Fi',
	'Adventure',
	'Fantasy',
	'Animation',
	'Rock',
	'Pop',
	'Jazz',
	'Classical',
	'Electronic',
	'Metal',
	'Fiction',
	'Non-Fiction',
	'Mystery',
	'Science Fiction',
	'Biography',
	'Self-Help',
	'Role-Playing',
	'Simulation',
	'Strategy',
	'Sports',
	'Puzzle',
	'Racing',
	'Documentary',
	'Superhero',
	'Paranormal',
	'Family',
	'Technology',
	'History',
	'Religion',
	'Travel',
	'Science',
	'Psychology',
	'Philosophy',
	'Poetry',
	'Educational',
	'Cyberpunk',
	'Time Travel',
	'DIY',
	'Nature',
	'Business',
	'Mathematics',
	'Crafts',
	'Fashion',
	'First-Person Shooter',
	'Multiplayer Online Battle Arena',
	'Photography',
	'Politics',
	'Cooking',
	'Anime',
	'Archeology',
	'Astronomy',
	'Biology',
	'Chemistry',
	'Computer Science',
	'Economics',
	'Engineering',
	'Geography',
	'Space',
	'Gaming'
]

const serverErr = "Something went wrong on our server, We'll try to fix it ASAP!"

export { Genres, serverErr }
